### ISSUE TITLE
Not working in Safari 15

### ISSUE THREAD

**Issue by Havnevik** [mmikkel/Reasons-Craft3#14]
Not working in Safari 15, shows everything and has no effect. Works perfectly in Chrome and Firefox.

System:
Safari 15.0
Craft Pro 3.7.16
Reasons 2.2.5

Developer console reports:

ReferenceError: Can't find variable: BroadcastChannel
init — DraftEditor.js:118
constructor — garnish.js:764
(anonym funksjon) — garnish.js:40
(anonym funksjon) — garnish.js:40

**Comment by mmikkel** [comment]
Did some further debugging and can confirm that Reasons not working in Safari is due to this error being thrown by Craft's core DraftEditor.js component. Looks like the issue was introduced quite recently in [this commit](https://github.com/craftcms/cms/commit/5373bf7a9f82dfd10cfbfed32bc32519e83334bf).

**Comment by mmikkel** [comment]
Craft 3.7.17.2 was just released with a fix for this.
